export const EMPLOYEE_TEXTS = {
  PAGE_TITLE: 'Funcionários',
  BREADCRUMB: 'Funcionários',
  NEW_EMPLOYEE: 'Novo Funcionário',
  EDIT_EMPLOYEE: 'Editar Funcionário',
  SINGULAR_LABEL: 'funcionário cadastrado',
  PLURAL_LABEL: 'funcionários cadastrados',
  SEARCH_PLACEHOLDER: 'Buscar por nome ou CPF...',
  NO_EMPLOYEES_FOUND: 'Nenhum funcionário encontrado',
  CREATE_EMPLOYEE_BUTTON: 'Criar Funcionário',
  SAVE_CHANGES: 'Salvar Alterações',
  CANCEL: 'Cancelar',
  BACK: 'Voltar',
  EDIT: 'Editar',
  EMPLOYEE_CREATED_SUCCESS: 'Funcionário criado com sucesso!',
  EMPLOYEE_UPDATED_SUCCESS: 'Funcionário atualizado com sucesso!',
  ERROR_CREATE: 'Erro ao criar funcionário',
  ERROR_UPDATE: 'Erro ao atualizar funcionário',
  REGISTER_NEW_EMPLOYEE: 'Cadastre um novo funcionário no sistema',
  UPDATE_EMPLOYEE_INFO: (name: string) => `Atualize as informações de ${name}`,
  EMPLOYEE_NUMBER: 'Matrícula',
  COLUMN_NAME: 'Nome',
  COLUMN_EMPLOYEE_NUMBER: 'Matrícula',
  COLUMN_CPF: 'CPF',
  COLUMN_EMAIL: 'E-mail',
  COLUMN_PHONE: 'Telefone',
  COLUMN_HIRE_DATE: 'Admissão',
  COLUMN_DRIVER: 'Motorista',
  COLUMN_HELPER: 'Ajudante',
  SECTION_PERSONAL_DATA: 'Dados Pessoais',
  SECTION_PROFESSIONAL_DATA: 'Dados Profissionais',
  SECTION_QUALIFICATIONS: 'Habilitações e Funções',
  SECTION_CNH: 'Carteira Nacional de Habilitação (CNH)',
  SECTION_PERSONAL_INFO: 'Informações Pessoais',
  SECTION_EMPLOYMENT_INFO: 'Informações de Emprego',
  SECTION_SYSTEM_INFO: 'Informações do Sistema',
  LABEL_FULL_NAME: 'Nome Completo',
  LABEL_CPF: 'CPF',
  LABEL_BIRTH_DATE: 'Data de Nascimento',
  LABEL_EMAIL: 'E-mail',
  LABEL_PHONE: 'Telefone',
  LABEL_EMPLOYEE_NUMBER_FIELD: 'Matrícula do Funcionário',
  LABEL_IDENTIFIER: 'Identificador Adicional',
  LABEL_HIRE_DATE: 'Data de Admissão',
  LABEL_TERMINATION_DATE: 'Data de Desligamento',
  LABEL_FUNCTIONS: 'Funções',
  LABEL_DRIVER: 'Motorista',
  LABEL_HELPER: 'Ajudante',
  LABEL_CNH_NUMBER: 'Número da CNH',
  LABEL_CNH_CATEGORY: 'Categoria',
  LABEL_CNH_EXPIRATION: 'Validade',
  LABEL_CNH_VALIDITY: 'Data de Validade',
  LABEL_PRIMARY_ADDRESS: 'Endereço Principal',
  LABEL_CREATED_AT: 'Criado em',
  LABEL_UPDATED_AT: 'Atualizado em',
  PLACEHOLDER_FULL_NAME: 'Nome completo do funcionário',
  PLACEHOLDER_CPF: '000.000.000-00',
  PLACEHOLDER_EMAIL: 'email@exemplo.com',
  PLACEHOLDER_PHONE: '(00) 00000-0000',
  PLACEHOLDER_EMPLOYEE_NUMBER: 'Ex: 001',
  PLACEHOLDER_IDENTIFIER: 'Ex: F001',
  PLACEHOLDER_CNH_NUMBER: '000000000',
  SELECT_CATEGORY: 'Selecione a categoria',
  SELECT_ONE_FUNCTION: 'Selecione pelo menos uma função',
  REQUIRED_FIELD: 'Campo obrigatório',
  OPTIONAL_FIELDS: 'Campos opcionais - podem ser preenchidos posteriormente',
  CNH_EXPIRED: 'Vencida',
  POSTAL_CODE: 'CEP',
} as const

export const EMPLOYMENT_STATUS_LABELS: Record<string, string> = {
  ACTIVE: 'Ativo',
  INACTIVE: 'Inativo',
  ON_LEAVE: 'Afastado',
  TERMINATED: 'Desligado',
} as const

export const CNH_TYPE_LABELS: Record<string, string> = {
  A: 'A - Motocicletas',
  B: 'B - Automóveis',
  C: 'C - Caminhões pequenos',
  D: 'D - Ônibus e caminhões',
  E: 'E - Caminhões articulados',
  AB: 'AB - A + B',
  AC: 'AC - A + C',
  AD: 'AD - A + D',
  AE: 'AE - A + E',
} as const

export const CNH_TYPE_OPTIONS = [
  { value: '', label: 'Selecione a categoria' },
  { value: 'A', label: 'A - Motos' },
  { value: 'B', label: 'B - Carros' },
  { value: 'AB', label: 'AB - Motos e Carros' },
  { value: 'C', label: 'C - Caminhões pequenos' },
  { value: 'D', label: 'D - Ônibus' },
  { value: 'E', label: 'E - Caminhões grandes' },
  { value: 'AC', label: 'AC - A + C' },
  { value: 'AD', label: 'AD - A + D' },
  { value: 'AE', label: 'AE - A + E' },
] as const
